# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 419)
        MainWindow.setMinimumSize(QtCore.QSize(450, 419))
        MainWindow.setMaximumSize(QtCore.QSize(450, 419))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/iacute-cone-do-instagram-colorido-by-Vexels.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(244, 244, 244);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.iniciar = QtWidgets.QPushButton(self.centralwidget)
        self.iniciar.setGeometry(QtCore.QRect(40, 320, 371, 41))
        self.iniciar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iniciar.setStyleSheet("QPushButton#iniciar {\n"
"    border: 1px solid  rgb(85, 170, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#iniciar:hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"QPushButton#iniciar:pressed {\n"
"    background-color: #f0f0f0;   \n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.iniciar.setObjectName("iniciar")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(40, 100, 161, 31))
        self.username.setStyleSheet("QLineEdit#username {\n"
"border: 1px solid  rgb(85, 170, 255);\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.username.setObjectName("username")
        self.senha = QtWidgets.QLineEdit(self.centralwidget)
        self.senha.setGeometry(QtCore.QRect(250, 100, 161, 31))
        self.senha.setStyleSheet("QLineEdit#senha {\n"
"border: 1px solid  rgb(85, 170, 255);\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha.setObjectName("senha")
        self.tag = QtWidgets.QLineEdit(self.centralwidget)
        self.tag.setGeometry(QtCore.QRect(40, 180, 161, 31))
        self.tag.setStyleSheet("QLineEdit#tag {\n"
"    border: 1px solid  rgb(85, 170, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.tag.setObjectName("tag")
        self.quantidade = QtWidgets.QLineEdit(self.centralwidget)
        self.quantidade.setGeometry(QtCore.QRect(250, 180, 161, 31))
        self.quantidade.setStyleSheet("QLineEdit#quantidade {\n"
"border: 1px solid  rgb(85, 170, 255);\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.quantidade.setText("")
        self.quantidade.setObjectName("quantidade")
        self.comentarios = QtWidgets.QLineEdit(self.centralwidget)
        self.comentarios.setGeometry(QtCore.QRect(40, 260, 161, 31))
        self.comentarios.setStyleSheet("QLineEdit#comentarios {\n"
"border: 1px solid  rgb(85, 170, 255);\n"
"border-radius: 5px;\n"
"}")
        self.comentarios.setObjectName("comentarios")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 70, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 150, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 150, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 160, 61, 20))
        self.label_5.setMinimumSize(QtCore.QSize(61, 20))
        self.label_5.setObjectName("label_5")
        self.comentarios_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.comentarios_2.setGeometry(QtCore.QRect(250, 260, 161, 31))
        self.comentarios_2.setStyleSheet("QLineEdit#comentarios_2 {\n"
"border: 1px solid  rgb(85, 170, 255);\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.comentarios_2.setObjectName("comentarios_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 230, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 230, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(110, 10, 231, 51))
        self.label_8.setStyleSheet("color: rgb(8, 8, 8);\n"
"font: 24pt \"MV Boli\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 150, 16, 16))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/icons/hashtag.png"))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 230, 16, 20))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/icons/comentarios.png"))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(250, 70, 16, 16))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/icons/padlock.png"))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(250, 150, 16, 16))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/icons/social-media.png"))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(250, 230, 16, 16))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/icons/comentarios.png"))
        self.label_14.setObjectName("label_14")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 70, 20, 20))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/icons/icons8-username-16.png"))
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bot Instagram V1.0"))
        self.iniciar.setText(_translate("MainWindow", "Iniciar"))
        self.label.setText(_translate("MainWindow", "Senha"))
        self.label_2.setText(_translate("MainWindow", "Username"))
        self.label_3.setText(_translate("MainWindow", "Tag"))
        self.label_4.setText(_translate("MainWindow", "Quantidade"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt;\">max: 800</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Comentários"))
        self.label_7.setText(_translate("MainWindow", "Comentários"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Bot Instagram</span></p></body></html>"))
import icons_tela
import botinsta


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
